### ISSUE TITLE
mZ1, mZ2 differential measurements

### ISSUE THREAD

**Issue by bonanomi** [bonanomi/FiducialXSFWK#19]
Produce differential measurements for mZ1 and mZ2 and make sure the framework works as expected for these two variables.

@AlessandroTarabini please share here the optimized binning for these two variables.

**Comment by AlessandroTarabini** [comment]
mZ1 [40, 65, 73, 80, 85, 90, 120]
mZ2 [12, 24, 28, 32, 40, 48, 65]

**Comment by bonanomi** [comment]
# Mass Z1
Analysis with mZ2 < 60 GeV cut, though it should not impact on the results, as described [here](https://github.com/bonanomi/FiducialXSFWK/issues/21).

![image](https://user-images.githubusercontent.com/19261234/101177270-e8b9ca00-3647-11eb-8f86-7f8d7ff3ff24.png)

Full set of results can be found [here](https://mbonanom.web.cern.ch/mbonanom/ZZ4l/fiducial/HIG-19-001/massZ1).

**Comment by bonanomi** [comment]
# Mass Z2

No cut on Z2 is applied.

![image](https://user-images.githubusercontent.com/19261234/101327033-69f2a600-386e-11eb-97cf-51b8a0a70561.png)

Full set of results can be found [here](https://mbonanom.web.cern.ch/mbonanom/ZZ4l/fiducial/HIG-19-001/massZ2/).
