### ISSUE TITLE
JES NP in fits

### ISSUE THREAD

**Issue by bonanomi** [bonanomi/FiducialXSFWK#25]
Try using lnN for JES NP to fix fits in 2D jets-related measurements.

**Comment by bonanomi** [comment]
JES NP crashes because not implemented in the skimmer for all the observables. Need to add the jes up/dn variations in the skimmer.

**Comment by bonanomi** [comment]
Inclusion of JES as lnN nuisance and not by modifying the pdf.

See: https://github.com/bonanomi/FiducialXSFWK/commit/8632501258242daac31106081b96b9243aa0e14a.

**Comment by AlessandroTarabini** [comment]
**New branch**->MELA
**New folder** -> coefficients/JES
New script RunJES.py to calculate JES lnN for both 1D and 2D variables.
Tested for pTj1 and pTj1 vs pTj1.
It is wise to check if the code works properly for each new variable.
