### ISSUE TITLE
ME Discriminants

### ISSUE THREAD

**Issue by bonanomi** [bonanomi/FiducialXSFWK#30]
Currently working on inclusion of ME discriminants in the main framework (GEN-level ones are the blocking issue). We will then update skimmer, RunCoefficient, and RunTemplates accordingly

cc @AlessandroTarabini

**Comment by AlessandroTarabini** [comment]
CJLST fwk updated to calculate ME probabilities at GEN-level (https://github.com/AlessandroTarabini/ZZAnalysis/tree/Run2_fiducial)
The updating of fiducial fwk is ongoing.

**Comment by AlessandroTarabini** [comment]
**New Branch** -> MELA
Framework updated to work with ME discriminants. New version of the skimmer (skimmer_v2). 
Tested for D0m.
