### ISSUE TITLE
GEN-Jets definition

### ISSUE THREAD

**Issue by bonanomi** [bonanomi/FiducialXSFWK#31]
Check the definition of GEN-Jets in the ntuples and make sure they are build using the correct approach and not the old one.

cc @AlessandroTarabini

**Comment by bonanomi** [comment]
At GEN-level jets are "cleaned" wrt the true MC particles, while we should create new Clean Gen jets wrt the gen.-particles that pass the topological selection

**Comment by AlessandroTarabini** [comment]
In the new version of the fwk (**new branch** -> MELA) there is an updated version of the skimmer (skim_v2) where this problem is fixed
