### ISSUE TITLE
QCD and PDF uncertainties

### ISSUE THREAD

**Issue by bonanomi** [bonanomi/FiducialXSFWK#9]
cc @AlessandroTarabini 

QCD and PDF uncertainties (as well as acceptance and efficiencies) for ggH powHeg and NNLOPS weighted events are computed using [`pdfUncertainty.py`](https://github.com/bonanomi/FiducialXSFWK/blob/main/coefficients/pdfUncertainty.py). Consider updating the script with the same structure as `RunCoefficients.py`. Maybe it's possible to include these calculations directly in `RunCoefficients.py`.

**Comment by AlessandroTarabini** [comment]
Done #16
